version: '3'
services:
    app:
      build: ./
      command: 
        - node 
        - /vote-system/app.js
      ports:
        - "3002:3002"
      environment:
        - NODE_ENV=dev
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_USER=root
        - DB_PWD=abc123123
        - DB_NAME=vote-system
        - ADMIN_EMAIL=admin@oo.xx
        - SEND_HOST=smtp.exmail.qq.com
        - SEND_EMAIL=
        - SEND_PWD=
        - HOSTURL=http://localhost:3002 
      links:
        - mysql
        - redis
    consumer:
      build: ./
      command: 
        - node 
        - /vote-system/consumer.js
      environment:
        - NODE_ENV=dev
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_USER=root
        - DB_PWD=abc123123
        - DB_NAME=vote-system
      links:
        - mysql
        - redis
    mysql:
      image: mysql:5.7
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=abc123123
    redis:
      image: redis:3.2
      ports:
        - "6379:6379"
